### ISSUE TITLE
Are other graph functionalities available?

### ISSUE THREAD

**Issue by pragun16** [HHRy/prawn-graph#23]
Are there basic graph functionalities like gridlines, resizing, removing the DOTS in a line chart etc? I cannot see them in the documentation so I doubt if such features are available. I am used to using DYGRAPHS charting library and would like to know if some of similar customization features are available. I really need gridlines and some basic functionalities for modifying how the graph looks. Please let me know if it is possbile. I appreciate the developer's effort though. Thanks!

**Comment by HHRy** [comment]
Hi there, right now there's no support for all of those things. You can, however, change the colour of the various parts of the charts.

It's planned to add gridlines in removing the dots in the future, but right now time's being spent on other things, like adding support for pie charts.

The underlying bug highlighted in #22 will need to be fixed properly before the gridlines stuff can be added, since the way the grid is drawn just now is pretty broken.

**Comment by pragun16** [comment]
I've been working on grids for a line chart for prawn-graph. However, I'm able to only generate the grids in a static manner as of now. Also, being a noob, I am really unsure if the way I've used are appropriate or not. Maybe if I feel that the work I've done is good enough for a PR then I shall do it later. However, as of now, I'd like to know if the fix for negative y-axis line is still on progess? How much time will it take for it to be usable in production?

**Comment by HHRy** [comment]
If you use the branch `22-negative-y-axis-labels`, it'll be fixed for your use case, but a proper fix will take a while to do properly, effectively negative values are plotted outside the box bounds defined for the graph just now, I need to rework how the whole canvas is drawn.

**Comment by pragun16** [comment]
okay then! i'm using the fix from `22-negative-y-axis-labels` for now and making minor changes into it. Thanks!
